"""add profile fields to user

Revision ID: 955e1d922fa9
Revises: e299d9645de7
Create Date: 2026-09-10 22:24:00.309478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '955e1d922fa9'
down_revision: Union[str, Sequence[str], None] = 'e299d9645de7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('experience', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('github_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('linkedin', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('telegram_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telegram_url')
    op.drop_column('users', 'linkedin')
    op.drop_column('users', 'github_url')
    op.drop_column('users', 'experience')
    # ### end Alembic commands ###
