"""split full_name into fields, add phone

Revision ID: f4ff7cfa6584
Revises: f26132b7c91f
Create Date: 2026-08-15 23:06:11.313975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4ff7cfa6584'
down_revision: Union[str, Sequence[str], None] = 'f26132b7c91f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('patronymic', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=30), nullable=True))
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'phone')
    op.drop_column('users', 'patronymic')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'last_name')
    # ### end Alembic commands ###
